export type Parameters = {
    destinationID: number,
    checkInDate: string,
    checkOutDate: string,
    numberOfRooms: number,
    accommodationTypes: string,
    CustomerCountry: string,
    language: string,
    currencies: string,
    numberOfAdults: number,
    numberOfChildren: number,
    hotelIDs?: string,
    childrenAges?: string,
    infant?: number,
    minPrice?: number,
    maxPrice?: number,
    minStarRating?: number,
    maxStarRating?: number,
    featureIds?: string,
    mealIds?: string,
    themeIds?: string,
    sortBy?: string,
    sortOrder?: string,
    exactDestinationMatch?: string,
    blockSuperdeal?: number,
    referencePointLatitude?: string,
    referencePointLongitude?: string,
    totalRoomsInBatch?: string,
}

export type OrderParams = {
    currency: string,
    language: string,
    email: string,
    checkInDate: string,
    checkOutDate: string,
    roomId: string,
    mealId: string,
    searchPrice: number,
    rooms: number,
    adults: number,
    children: number,
    infant: number,
    yourRef: string,
    customerCountry: string,
    hotelId?: number,
    roomtypeId?: number,
    blockSuperDeal?: boolean,
    showPriceBreakdown?: string,
    B2C?: string,
}
